### ISSUE TITLE
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.AmosKorir:mrz_scanner:0.0.1.

### ISSUE THREAD

**Issue by Fanom2813** [AmosKorir/MRZ-Scanner#1]
am not able to build the project 
im getting these errors : 

- Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.AmosKorir:mrz_scanner:0.0.1.
- Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.AmosKorir:mrz_scanner:0.0.1.
- Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.AmosKorir:mrz_scanner:0.0.1.

**Comment by AmosKorir** [comment]
In new android project structure, you need to add jitpack repository to setting.gradle. Below is  an example .

```kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven{url 'https://jitpack.io'}
    }
}
rootProject.name = "TestCode"
include ':app'

``

**Comment by Fanom2813** [comment]
i have the same configuration but still fails
